export type PageKey =
    | "home"
    | "students"
    | "teachers"
    | "admins"
    | "parents"
    | "classes"
    | "subjects"
    | "schedule"
    | "attendance"
    | "finance"
    | "announcements"
    | "contact"
    | "files"
    | "settings"
    | "audit";